"use client";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Brain, Users, Dumbbell, ShoppingCart, BookOpen, Heart } from "lucide-react";
import { cn } from "@/lib/utils";

const features = [
  {
    icon: Brain,
    title: "AI-Powered Plans",
    description: "Personalized workout and nutrition plans generated by advanced AI algorithms tailored to your goals.",
    badge: "New",
  },
  {
    icon: Users,
    title: "Expert Trainers",
    description: "30+ certified trainers ready to guide you with real-time booking and video sessions.",
    badge: "Popular",
  },
  {
    icon: Dumbbell,
    title: "24/7 Access",
    description: "Premium equipment and facilities available around the clock at all locations across Australia.",
    badge: null,
  },
  {
    icon: ShoppingCart,
    title: "Premium Marketplace",
    description: "Curated fitness products, supplements, and equipment delivered to your door.",
    badge: null,
  },
  {
    icon: BookOpen,
    title: "Community Hub",
    description: "Connect with fellow members, share progress, and join challenges in our thriving community.",
    badge: null,
  },
  {
    icon: Heart,
    title: "Health Tracking",
    description: "Comprehensive progress tracking with detailed analytics and insights.",
    badge: null,
  },
];

export function PremiumFeatures() {
  return (
    <section className="relative py-24 lg:py-32">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="mx-auto mb-16 max-w-3xl text-center">
          <Badge variant="accent" className="mb-4">
            Complete Fitness Ecosystem
          </Badge>
          <h2 className="mb-4 text-3xl font-bold tracking-tight text-white sm:text-4xl md:text-5xl">
            Everything You Need in
            <span className="block mt-2">One Platform</span>
          </h2>
          <p className="text-lg leading-relaxed text-white/70">
            From AI-powered personalized plans to expert trainers, premium marketplace, 
            and thriving community - we've built the ultimate fitness ecosystem for your success.
          </p>
        </div>

        {/* Features Grid */}
        <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {features.map((feature, index) => {
            const Icon = feature.icon;
            return (
              <Card
                key={feature.title}
                variant="premium"
                className={cn(
                  "group transition-all duration-300 hover:-translate-y-1",
                  "hover:bg-white/[0.07]"
                )}
              >
                <CardHeader>
                  <div className="mb-4 flex items-start justify-between">
                    <div className="rounded-xl bg-white/5 p-3 backdrop-blur-sm">
                      <Icon className="h-6 w-6 text-white" />
                    </div>
                    {feature.badge && (
                      <Badge variant="accent" className="text-xs">
                        {feature.badge}
                      </Badge>
                    )}
                  </div>
                  <CardTitle className="text-xl font-semibold text-white">
                    {feature.title}
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <CardDescription className="text-white/70">
                    {feature.description}
                  </CardDescription>
                </CardContent>
              </Card>
            );
          })}
        </div>
      </div>
    </section>
  );
}
