import { MetadataRoute } from 'next';

/**
 * Robots.txt for search engine crawler control
 * Automatically generated by Next.js
 */
export default function robots(): MetadataRoute.Robots {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://derrimut-platform.vercel.app';
  
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/api/',
          '/admin/',
          '/super-admin/',
          '/profile/',
          '/location-admin/',
          '/trainer/',
          '/booking-success/',
          '/stripe-debug/',
          '/webhook-test/',
          '/test-booking/',
          '/demo-dashboard/',
          '/new-design-system/',
          '/_next/',
          '/private/',
        ],
      },
      {
        userAgent: 'Googlebot',
        allow: '/',
        disallow: [
          '/api/',
          '/admin/',
          '/super-admin/',
          '/profile/',
          '/location-admin/',
          '/trainer/',
        ],
      },
      {
        userAgent: 'Bingbot',
        allow: '/',
        disallow: [
          '/api/',
          '/admin/',
          '/super-admin/',
          '/profile/',
        ],
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
  };
}

